name: Update Douban Activity

on:
  schedule:
    # 每天运行一次
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-douban:
    name: Update Douban Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lisongx/douban-readme-stats@main
        with:
          #
          # 核心配置：把 'YOUR_DOUBAN_USER_ID' 换成你的豆瓣 ID
          #
          douban_id: ${{ secrets.DOUBAN_USER_ID }}
          readme_path: "./README.md"
          #
          # 确保这里的标记和你的 README.md 文件里一致
          #
          douban_start_comment: "<!-- douban starts -->"
          douban_end_comment: "<!-- douban ends -->"
