name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # 确保你已经在 Settings > Secrets 里设置了 WAKATIME_API_KEY
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # 这里的标记必须和你第 1 步在 README.md 里改的一致
          WAKA_START: "<!-- code_time starts -->"
          WAKA_END: "<!-- code_time ends -->"
