name: Update Douban Stats

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行
  workflow_dispatch: # 允许手动运行

permissions:
  contents: write # 保留写入权限

jobs:
  update-readme:
    name: Update README with Douban RSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # 换成一个可以读取 RSS 的 Action
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # RSS 链接
          feed_list: "https://www.douban.com/feed/people/268128201/interests"
          
          # 对应 README 中的 comment_tag_name: "douban"
          
          # (可选) 您想显示的最大条目数
          # max_post_count: 5
