name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次
  workflow_dispatch: # 允许手动运行

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anmol098/waka-readme-stats@master # 使用这个 Action
        with:
          # 必填项
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

