name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行
  workflow_dispatch: # 允许手动运行

permissions:
  contents: write # 写入权限 (需要第1步的设置)

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # 注意：我们更换了 Action 的名字
      - uses: athul/waka-readme-stats@master 
        with:
          # 必填项
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          
          # --- 以下是您想要的自定义选项 ---
          
          # (可选) 设置您想要的标题
          TITLE: "This Week I Code With"
          
          # (可选) 设置统计的时间范围
          TIME_RANGE: "last_7_days" 
          
          # (可选) 隐藏其他信息，只显示语言
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
